crypto-bug-hunters/bug-buster

- frontend/src/app/bounty/[bountyId]/page.tsx
- frontend/src/app/page.tsx
- frontend/src/components/bountyStatus.tsx
- frontend/src/model/bountyStatus.ts
- frontend/src/utils/bounty.tsx
> fix: use `block.timestamp` for bounty status badge

- Makefile
Created release [kernel](https://github.com/crypto-bug-hunters/bugless/releases/tag/kernel)
Closes #73
> Fix kernel download URL

- README.md
Some dependencies aren't actually necessary on the host machine, as they are installed and run inside a Docker container:
- Back-end: `go`
- Examples: `tar`
- Tests: `lua`
> Fix dependency table

- cli/cmd/send.go
- cli/cmd/test.go
- contract/main.go
- go.mod
- go.sum
Rollmelette v0.1.1 fixes a bug related to ERC-20 withdrawals, which we plan to support.
Also, the Rollmelette repository migrated to its own organization on GitHub.
> Bump Rollmelette from v0.1.0 to v0.1.1

- cli/cmd/state.go
- contract/main.go
- frontend/src/app/bounty/[bountyId]/exploit/page.tsx
- frontend/src/app/bounty/[bountyId]/page.tsx
- frontend/src/app/bounty/[bountyId]/sponsor/page.tsx
- frontend/src/app/header.tsx
- frontend/src/app/page.tsx
- frontend/src/app/shell.tsx
- frontend/src/app/voucher/page.tsx
- frontend/src/components/bountyStatus.tsx
- frontend/src/components/copy.tsx
- frontend/src/components/profileCard.tsx
- frontend/src/model/reader.ts
- frontend/src/model/state.ts
- frontend/src/utils/bounty.tsx
- populate.sh
- shared/bugless.go
- tests/tests.lua
Also, removes several unused imports
Closes #59
> Serialize state to JSON with keys in `camelCase`

- tests/bounties/solidity-bounty/Dockerfile
The `-j` option makes the build unstable for some reason.
Removing it makes the build more stable at the expense of compile time.
> Fix Solidity bounty Dockerfile

- frontend/.dockerignore
- frontend/.eslintrc.json
- frontend/Dockerfile
- frontend/next.config.js
Closes #49 
PS1: @guidanoli there is only one comment in .eslintrc.json that I would like to keep because I added a "hack". If you create an empty project it is not needed so I would like to register why there is "next/babel" on that file, ok? But if you still don't like it, I can remove.
PS2: @endersonmaia now it can be easier if you need to make any change on the branch and update the PR. 😉
> Frontend containerization

- frontend/.eslintrc.json
Sources:
- [StackOverflow question](https://stackoverflow.com/questions/71662525/failed-to-load-config-next-babel-to-extend-from-eslintrc-json)
- [Next.js GitHub issue](https://github.com/vercel/next.js/discussions/24254)
Closes #96
> Fix `.eslintrc.json`

- Dockerfile
> Copy bounties to `/bounties/examples`

- README.md
The README is still featuring the old name (Bugless).
This PR changes it to reflect the new one (Bugbuster)
> Update README to reflect new name

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/app/bounty/[bountyId]/exploit/page.tsx
- frontend/src/app/bounty/[bountyId]/page.tsx
- frontend/src/app/bounty/[bountyId]/sponsor/page.tsx
- frontend/src/app/bounty/[bountyId]/utils.tsx
- frontend/src/app/bounty/create/page.tsx
- frontend/src/app/page.tsx
- frontend/src/app/voucher/page.tsx
- frontend/src/hooks/bug-buster.tsx
- frontend/src/model/inputs.ts
- frontend/src/model/reader.ts
- frontend/src/model/state.ts
- frontend/src/utils/voucher.tsx
Sorry for not being able to chop this PR into several smaller commits.
I'll highlight the most important changes:
- Rename reader hooks (e.g. `GetBounty` :arrow_right: `useBounty`)
- Rewrite reader hooks with `useState`, `useEffect`, safe JSON parsing, and type guards.
- Render reader hooks in "loading" and "error" states.
- Remove `ethers` from the list of dependencies, using `viem` instead
> Refactor front-end

- frontend/src/app/header.tsx
- frontend/src/app/notification/page.tsx
Draft PR to mainly bring a words of caution proposal for review and alignment.
It is missing final layout adjustments and naming review.
> Notification bar

- frontend/src/app/explore/page.tsx
- frontend/src/app/page.tsx
> Create a landing page

- README.md
- cli/cmd/send.go
- cli/cmd/sponsor.go
- contract/main.go
- frontend/src/app/bounty/[bountyId]/exploit/page.tsx
- frontend/src/app/bounty/[bountyId]/page.tsx
- frontend/src/app/bounty/[bountyId]/sponsor/page.tsx
- frontend/src/app/bounty/create/page.tsx
- frontend/src/app/voucher/page.tsx
- frontend/src/hooks/bug-buster.tsx
- frontend/src/model/inputs.ts
- frontend/src/model/state.ts
- frontend/src/utils/erc20.tsx
- frontend/src/utils/form.ts
- frontend/src/utils/transactionStatus.ts
- frontend/src/utils/voucher.tsx
- shared/bug-buster.go
- tests/tests.lua
> Accept ERC-20 tokens instead of ETH

- tests/bounties/solidity-bounty/start.sh
From the github repo @edubart discovered some known issues that could break the bounty. The following preconditions were added to the assertion script:
- Require the 0.8.26 solidity version
- Reject exploit code containing the experimental directive
- Reject exploit code if it contain non-ascii character
The result of the new assertion script when we submit the code that allowed Eduardo to break the bounty is presented below.
The goal is to deploy it asap while so people can continue playing with it on testnet and meanwhile redo the analysis of the solidity compiler github repo to check if there are other known issues to be added as preconditions.
> fix: check preconditions before running exploit code for the solidity bounty

- frontend/src/app/notification/page.tsx
- frontend/src/utils/links.tsx
We created a telegram group to be our official community for Bug Buster. This group will be a direct line between users and our developers.
What to expect:
Direct Contact with Developers: Share your feedback, report issues, and suggest features directly to the team.
Exclusive Updates: Be the first to know about new features, updates, and special events.
> fix: Replace Discord thread by the new Telegram group

- cli/cmd/bounty.go
- populate.sh
- tests/bounties/busybox-bounty/info.json
- tests/bounties/lua-bounty/info.json
- tests/bounties/solidity-bounty/info.json
- tests/bounties/sqlite-bounty/info.json
This is how the `/explore` page looks like after running the populate script:
> Fix populate script

- .github/workflows/build.yml
Makes use of the new `--json` option of the `cartesi deploy build` command (added in 0.16.0).
> Build Cartesi Node image in the CI

- frontend/src/app/bounty/[bountyId]/exploit/page.tsx
- frontend/src/app/bounty/[bountyId]/page.tsx
- frontend/src/app/bounty/[bountyId]/sponsor/page.tsx
- frontend/src/app/bounty/create/page.tsx
- frontend/src/app/explore/page.tsx
- frontend/src/app/footer.tsx
- frontend/src/app/header.tsx
- frontend/src/app/notification/page.tsx
- frontend/src/app/page.tsx
- frontend/src/app/shell.tsx
- frontend/src/app/voucher/page.tsx
- frontend/src/components/copy.tsx
- frontend/src/components/profileCard.tsx
@claudioantonio @guidanoli I realised that I don't have write permissions too late, therefore created a Fork and committed all the tweaks in the forked repo. Hopefully will work for you.
> Responsive optimizations

- .github/workflows/build.yml
- .gitignore
- Makefile
- README.md
- package.json
- pnpm-lock.yaml
- populate.sh
- tests/bounties/solidity-bounty/Dockerfile
I can confirm the Cartesi Machine template hash and the Cartesi Node image hash are the same, when building with Cartesi CLI 0.15.0 or 0.16.0. Cartesi CLI 0.16.0 adds a `--json` option to the `cartesi deploy build` command, which allows us to automate the build process for the Cartesi Node image.
> Specify Cartesi CLI version in `package.json`

- .github/workflows/build.yml
Reference: [`paths-ignore` on GitHub Docs](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
> Add `paths-ignore` filter to `push` events on `main` for build workflow

- Dockerfile
- tests/Dockerfile
- tests/bounties/busybox-bounty/Dockerfile
- tests/bounties/busybox-bounty/Makefile
- tests/bounties/lua-bounty/Dockerfile
- tests/bounties/lua-bounty/Makefile
- tests/bounties/solidity-bounty/Dockerfile
- tests/bounties/sqlite-bounty/Dockerfile
- tests/bounties/sqlite-bounty/Makefile
> Make build reproducible

- populate.sh
- tests/bounties/Makefile
- tests/bounties/solidity-bounty/Makefile
- tests/bounties/solidity-bounty/info.json
Solidity 0.8.27 was officially launched then we will close the current bounty for 0.8.26 and open a new one for the new release.
> Create bounty for solidity 0.8.27

- package.json
When [`corepack`](https://nodejs.org/api/corepack.html) is enabled, it looks for this field when `pnpm` is executed.
Source: https://nodejs.org/api/packages.html#packagemanager
> Specify package manager for root package

- Dockerfile
This PR will change the main Dockerfile to use the `apt update --snapshot` option to lock the Ubuntu repository into a specific point in time.
See: https://snapshot.ubuntu.com
So, we don't need to pin package versions anymore and get the guarantee that the package versions used and their dependencies will always be the same.
When we want to change the date, we just need to change the `ARG NOBLE_DATE` to a desired values.
I'm reusing this same `ARG` to the `apt update --snapshot=` and for the Oficial Ubuntu Docker Image tag that has a date, like `ubuntu:noble-20240801`.
If we desire to change this date in the future, we can look what's the latest dated version available at https://hub.docker.com/_/ubuntu
> Noble Numbat is the codename for the latest Ubuntu LTS version, which is 24.04.
> feat: use `apt update --snapshot` for reproducibility

- .github/workflows/build.yml
- Dockerfile
- go.mod
- go.sum
This PR will add a scan step into the CI that will upload the SARIF output to GitHub, and it will show security alerts like the ones in this link https://github.com/crypto-bug-hunters/bug-buster/security/code-scanning?query=pr%3A155+is%3Aopen
We should define some policy on where to enforce CI to fail at a certain level of vulnerability or not.
Currently, it's configured not to fail.
> Add grype vulnerability scanner to CI

- .github/workflows/build.yml
Source: https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
> Give `security-events: write` permission to CI

- Dockerfile
This PR will use `Dockerfile`'s ADD instead of `curl` and not having to install `curl` in the final image.
With that, we go from [11 CVEs](https://github.com/crypto-bug-hunters/bug-buster/issues/159) to only 5 according to `grype`´s output.
```
NAME            INSTALLED            FIXED-IN  TYPE  VULNERABILITY   SEVERITY   
busybox-static  1:1.36.1-6ubuntu3.1            deb   CVE-2023-42366  Medium      
busybox-static  1:1.36.1-6ubuntu3.1            deb   CVE-2023-39810  Medium      
libgcrypt20     1.10.3-2build1                 deb   CVE-2024-2236   Medium      
libssl3t64      3.0.13-0ubuntu3.4              deb   CVE-2024-41996  Medium      
openssl         3.0.13-0ubuntu3.4              deb   CVE-2024-41996  Medium
```
> Remove curl dependency from final image
